# Azure VM Local Database Configuration
# This profile ensures Azure deployment NEVER uses external cloud databases

knife4j:
  production: false
  enable: true
  basic:
    enable: false
    username: admin
    password: admin
  setting:
    enableFooter: false

# Server configuration for Azure VM
server:
  port: ${SERVER_PORT:8002}
  address: 0.0.0.0

spring:
  datasource:
    druid:
      # AZURE VM LOCAL DATABASE ONLY
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/xiaozhi_db?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&nullCatalogMeansCurrent=true&useSSL=false&allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true
      username: xiaozhi_user
      password: xiaozhi_password123

      initial-size: 5
      max-active: 20
      min-idle: 5
      max-wait: 6000
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      stat-view-servlet:
        enabled: false
      filter:
        stat:
          log-slow-sql: true
          slow-sql-millis: 1000
          merge-sql: false
        wall:
          config:
            multi-statement-allow: true

  data:
    redis:
      # AZURE VM LOCAL REDIS ONLY
      host: localhost
      port: 6379
      password: # No password for local Redis
      database: 0
      timeout: 10000ms
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
        shutdown-timeout: 100ms

# Liquibase configuration
liquibase:
  change-log: classpath:db/changelog/db.changelog-master.yaml
  enabled: true
  drop-first: false