knife4j:
  production: false
  enable: true
  basic:
    enable: false
    username: admin
    password: admin
  setting:
    enableFooter: false

# Server configuration
server:
  port: ${SERVER_PORT:8002}
  address: 0.0.0.0
  secret: b4f9775a-a022-426d-b459-018eab1843c0

# Management endpoints for health checks
management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

# Redis configuration for captcha
renren:
  redis:
    open: true

spring:
  datasource:
    druid:
      # Local Docker MySQL database
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3307/manager_api?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&nullCatalogMeansCurrent=true&useSSL=false&allowPublicKeyRetrieval=true
      username: manager
      password: managerpassword

      initial-size: 5
      max-active: 20
      min-idle: 5
      max-wait: 6000
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      stat-view-servlet:
        enabled: false
      filter:
        stat:
          log-slow-sql: true
          slow-sql-millis: 1000
          merge-sql: false
        wall:
          config:
            multi-statement-allow: true

  data:
    redis:
      # Local Docker Redis
      host: localhost
      port: 6380
      password: redispassword
      database: 0
      timeout: 10000ms
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
        shutdown-timeout: 100ms
