# Tomcat
server:
  tomcat:
    uri-encoding: UTF-8
    threads:
      max: 1000
      min-spare: 30
  port: 8002
  servlet:
    context-path: /toy
    session:
      cookie:
        http-only: true

spring:
  # 环境 dev|test|prod
  profiles:
    active: dev # Using dev profile with Railway database configuration
  messages:
    encoding: UTF-8
    basename: i18n/messages
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
      enabled: true
  main:
    allow-bean-definition-overriding: true

knife4j:
  enable: true
  basic:
    enable: false
    username: admin
    password: admin
  setting:
    enableFooter: false

renren:
  redis:
    open: true
  xss:
    enabled: true
    exclude-urls:

# Textbook RAG Configuration
textbook:
  upload:
    directory: D:/cheekofinal/xiaozhi-esp32-server/main/manager-api/uploadfile/textbooks
  chunk:
    size: 512
    overlap: 50

# External Services
xiaozhi:
  python:
    server:
      url: http://localhost:8003

# RAG System Configuration
rag:
  qdrant:
    url: https://1198879c-353e-49b1-bfab-8f74004aaf6d.eu-central-1-0.aws.cloud.qdrant.io:6333
    api-key: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2Nlc3MiOiJtIn0.wKcnr3q8Sq4tb7JzPGnZbuxm9XpfDNutdfFD8mCDlrc
    timeout: 30
    tls: true
    default-collection: mathematics_std6
  embedding:
    service-url: http://localhost:8003/embeddings  # xiaozhi-server embedding endpoint
    model: BAAI/bge-large-en-v1.5
    dimensions: 768
    batch-size: 32
    timeout: 60
  processing:
    max-chunk-tokens: 512
    chunk-overlap: 50
    hierarchical-chunking: true
    min-importance-score: 0.3
    parallel-processing: true
    processing-threads: 4
  cache:
    enabled: true
    ttl: 3600
    max-size: 100MB
    key-prefix: "rag:"

# Legacy configurations (maintained for compatibility)
# Vector Database (Qdrant Cloud)
qdrant:
  url: https://1198879c-353e-49b1-bfab-8f74004aaf6d.eu-central-1-0.aws.cloud.qdrant.io:6333
  api-key: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2Nlc3MiOiJtIn0.wKcnr3q8Sq4tb7JzPGnZbuxm9XpfDNutdfFD8mCDlrc

# Embeddings (Voyage AI)
voyage:
  api-key: pa-1ai2681JWAAiaAGVPzmVHhiEWmOmwPwVGAfYBBi-oBL

#mybatis
mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: xiaozhi.modules.*.entity
  global-config:
    #数据库相关配置
    db-config:
      #主键类型
      id-type: ASSIGN_ID
    banner: false
  #原生配置
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    call-setters-on-nulls: true
    jdbc-type-for-null: "null"
  configuration-properties:
    prefix:
    blobType: BLOB
    boolValue: TRUE
