-- Local short-term memory can set independent LLM
UPDATE ai_model_provider SET fields =  '[{"key":"llm","label":"LLM Model","type":"string"}]' WHERE  id = 'SYSTEM_Memory_mem_local_short';
UPDATE ai_model_config SET config_json =  '{"type": "mem_local_short", "llm": "LLM_ChatGLMLLM"}' WHERE  id = 'Memory_mem_local_short';

-- Add Huoshan Double Stream TTS provider and model configuration
DELETE FROM ai_model_provider WHERE id = 'SYSTEM_TTS_HSDSTTS';
INSERT INTO ai_model_provider (id, model_type, provider_code, name, fields, sort, creator, create_date, updater, update_date) VALUES
('SYSTEM_TTS_HSDSTTS', 'TTS', 'huoshan_double_stream', 'Huoshan Double Stream TTS', '[{"key":"ws_url","label":"WebSocket Address","type":"string"},{"key":"appid","label":"Application ID","type":"string"},{"key":"access_token","label":"Access Token","type":"string"},{"key":"resource_id","label":"Resource ID","type":"string"},{"key":"speaker","label":"Default Voice","type":"string"}]', 13, 1, NOW(), 1, NOW());

DELETE FROM ai_model_config WHERE id = 'TTS_HuoshanDoubleStreamTTS';
INSERT INTO ai_model_config VALUES ('TTS_HuoshanDoubleStreamTTS', 'TTS', 'HuoshanDoubleStreamTTS', 'Huoshan Double Stream TTS', FALSE, TRUE, '{"type": "huoshan_double_stream", "ws_url": "wss://openspeech.bytedance.com/api/v3/tts/bidirection", "appid": "your_huoshan_tts_appid", "access_token": "your_huoshan_tts_access_token", "resource_id": "volc.service_type.10029", "speaker": "zh_female_wanwanxiaohe_moon_bigtts"}', NULL, NULL, 16, NULL, NULL, NULL, NULL);

-- Huoshan Double Stream TTS model configuration documentation
UPDATE ai_model_config SET
doc_link = 'https://console.volcengine.com/speech/service/10007',
remark = 'Huoshan TTS service configuration instructions:
1. Visit https://www.volcengine.com/ to register and activate Huoshan Engine account
2. Visit https://console.volcengine.com/speech/service/10007 to activate TTS large model service, purchase voices
3. Get appid and access_token at bottom of page
5. Resource ID fixed as: volc.service_type.10029 (Large model TTS and mixing)
6. Fill into configuration file' WHERE id = 'TTS_HuoshanDoubleStreamTTS';


-- Add Huoshan Double Stream TTS voices
DELETE FROM ai_tts_voice WHERE tts_model_id = 'TTS_HuoshanDoubleStreamTTS';
INSERT INTO ai_tts_voice (id, tts_model_id, name, tts_voice, languages, voice_demo, remark, sort, creator, create_date, updater, update_date) VALUES ('TTS_HuoshanDoubleStreamTTS_0001', 'TTS_HuoshanDoubleStreamTTS', 'Skye', 'zh_female_shuangkuaisisi_moon_bigtts', 'Chinese, English', 'https://lf3-static.bytednsdoc.com/obj/eden-cn/lm_hz_ihsph/ljhwZthlaukjlkulzlp/portal/bigtts/Skye.mp3', NULL, 1, 1, NOW(), 1, NOW());
INSERT INTO ai_tts_voice (id, tts_model_id, name, tts_voice, languages, voice_demo, remark, sort, creator, create_date, updater, update_date) VALUES ('TTS_HuoshanDoubleStreamTTS_0002', 'TTS_HuoshanDoubleStreamTTS', 'Alvin', 'zh_male_wennuanahu_moon_bigtts', 'Chinese, English', 'https://lf3-static.bytednsdoc.com/obj/eden-cn/lm_hz_ihsph/ljhwZthlaukjlkulzlp/portal/bigtts/Alvin.mp3', NULL, 2, 1, NOW(), 1, NOW());
INSERT INTO ai_tts_voice (id, tts_model_id, name, tts_voice, languages, voice_demo, remark, sort, creator, create_date, updater, update_date) VALUES ('TTS_HuoshanDoubleStreamTTS_0003', 'TTS_HuoshanDoubleStreamTTS', 'Brayan', 'zh_male_shaonianzixin_moon_bigtts', 'Chinese, English', 'https://lf3-static.bytednsdoc.com/obj/eden-cn/lm_hz_ihsph/ljhwZthlaukjlkulzlp/portal/bigtts/Brayan.mp3', NULL, 3, 1, NOW(), 1, NOW());
INSERT INTO ai_tts_voice (id, tts_model_id, name, tts_voice, languages, voice_demo, remark, sort, creator, create_date, updater, update_date) VALUES ('TTS_HuoshanDoubleStreamTTS_0004', 'TTS_HuoshanDoubleStreamTTS', 'Neighbor Girl', 'zh_female_linjianvhai_moon_bigtts', 'Chinese', 'https://lf3-static.bytednsdoc.com/obj/eden-cn/lm_hz_ihsph/ljhwZthlaukjlkulzlp/portal/bigtts/%E9%82%BB%E5%AE%B6%E5%A5%B3%E5%AD%A9.mp3', NULL, 4, 1, NOW(), 1, NOW());
INSERT INTO ai_tts_voice (id, tts_model_id, name, tts_voice, languages, voice_demo, remark, sort, creator, create_date, updater, update_date) VALUES ('TTS_HuoshanDoubleStreamTTS_0005', 'TTS_HuoshanDoubleStreamTTS', 'Scholarly Uncle', 'zh_male_yuanboxiaoshu_moon_bigtts', 'Chinese', 'https://lf3-static.bytednsdoc.com/obj/eden-cn/lm_hz_ihsph/ljhwZthlaukjlkulzlp/portal/bigtts/%E6%B8%8A%E5%8D%9A%E5%B0%8F%E5%8F%94.mp3', NULL, 5, 1, NOW(), 1, NOW());
INSERT INTO ai_tts_voice (id, tts_model_id, name, tts_voice, languages, voice_demo, remark, sort, creator, create_date, updater, update_date) VALUES ('TTS_HuoshanDoubleStreamTTS_0006', 'TTS_HuoshanDoubleStreamTTS', 'Sunny Youth', 'zh_male_yangguangqingnian_moon_bigtts', 'Chinese', 'https://lf3-static.bytednsdoc.com/obj/eden-cn/lm_hz_ihsph/ljhwZthlaukjlkulzlp/portal/bigtts/%E9%98%B3%E5%85%89%E9%9D%92%E5%B9%B4.mp3', NULL, 6, 1, NOW(), 1, NOW());
INSERT INTO ai_tts_voice (id, tts_model_id, name, tts_voice, languages, voice_demo, remark, sort, creator, create_date, updater, update_date) VALUES ('TTS_HuoshanDoubleStreamTTS_0007', 'TTS_HuoshanDoubleStreamTTS', 'Harmony', 'zh_male_jingqiangkanye_moon_bigtts', 'Chinese, English', 'https://lf3-static.bytednsdoc.com/obj/eden-cn/lm_hz_ihsph/ljhwZthlaukjlkulzlp/portal/bigtts/Harmony.mp3', NULL, 7, 1, NOW(), 1, NOW());
INSERT INTO ai_tts_voice (id, tts_model_id, name, tts_voice, languages, voice_demo, remark, sort, creator, create_date, updater, update_date) VALUES ('TTS_HuoshanDoubleStreamTTS_0008', 'TTS_HuoshanDoubleStreamTTS', 'Taiwan Xiao He', 'zh_female_wanwanxiaohe_moon_bigtts', 'Chinese', 'https://lf3-static.bytednsdoc.com/obj/eden-cn/lm_hz_ihsph/ljhwZthlaukjlkulzlp/portal/bigtts/%E6%B9%BE%E6%B9%BE%E5%B0%8F%E4%BD%95.mp3', NULL, 8, 1, NOW(), 1, NOW());
INSERT INTO ai_tts_voice (id, tts_model_id, name, tts_voice, languages, voice_demo, remark, sort, creator, create_date, updater, update_date) VALUES ('TTS_HuoshanDoubleStreamTTS_0009', 'TTS_HuoshanDoubleStreamTTS', 'Bay Area Uncle', 'zh_female_wanqudashu_moon_bigtts', 'Chinese', 'https://lf3-static.bytednsdoc.com/obj/eden-cn/lm_hz_ihsph/ljhwZthlaukjlkulzlp/portal/bigtts/%E6%B9%BE%E5%8C%BA%E5%A4%A7%E5%8F%94.mp3', NULL, 9, 1, NOW(), 1, NOW());
INSERT INTO ai_tts_voice (id, tts_model_id, name, tts_voice, languages, voice_demo, remark, sort, creator, create_date, updater, update_date) VALUES ('TTS_HuoshanDoubleStreamTTS_0010', 'TTS_HuoshanDoubleStreamTTS', 'Cute Sichuan Girl', 'zh_female_daimengchuanmei_moon_bigtts', 'Chinese', 'https://lf3-static.bytednsdoc.com/obj/eden-cn/lm_hz_ihsph/ljhwZthlaukjlkulzlp/portal/bigtts/%E5%91%86%E8%90%8C%E5%B7%9D%E5%A6%B9.mp3', NULL, 10, 1, NOW(), 1, NOW());
INSERT INTO ai_tts_voice (id, tts_model_id, name, tts_voice, languages, voice_demo, remark, sort, creator, create_date, updater, update_date) VALUES ('TTS_HuoshanDoubleStreamTTS_0011', 'TTS_HuoshanDoubleStreamTTS', 'Guangzhou Brother', 'zh_male_guozhoudege_moon_bigtts', 'Chinese', 'https://lf3-static.bytednsdoc.com/obj/eden-cn/lm_hz_ihsph/ljhwZthlaukjlkulzlp/portal/bigtts/%E5%B9%BF%E5%B7%9E%E5%BE%B7%E5%93%A5.mp3', NULL, 11, 1, NOW(), 1, NOW());
INSERT INTO ai_tts_voice (id, tts_model_id, name, tts_voice, languages, voice_demo, remark, sort, creator, create_date, updater, update_date) VALUES ('TTS_HuoshanDoubleStreamTTS_0012', 'TTS_HuoshanDoubleStreamTTS', 'Beijing Boy', 'zh_male_beijingxiaoye_moon_bigtts', 'Chinese', 'https://lf3-static.bytednsdoc.com/obj/eden-cn/lm_hz_ihsph/ljhwZthlaukjlkulzlp/portal/bigtts/%E5%8C%97%E4%BA%AC%E5%B0%8F%E7%88%B7.mp3', NULL, 12, 1, NOW(), 1, NOW());
INSERT INTO ai_tts_voice (id, tts_model_id, name, tts_voice, languages, voice_demo, remark, sort, creator, create_date, updater, update_date) VALUES ('TTS_HuoshanDoubleStreamTTS_0013', 'TTS_HuoshanDoubleStreamTTS', 'Haoyu Brother', 'zh_male_haoyuxiaoge_moon_bigtts', 'Chinese', 'https://lf3-static.bytednsdoc.com/obj/eden-cn/lm_hz_ihsph/ljhwZthlaukjlkulzlp/portal/bigtts/%E6%B5%A9%E5%AE%87%E5%B0%8F%E5%93%A5.mp3', NULL, 13, 1, NOW(), 1, NOW());
INSERT INTO ai_tts_voice (id, tts_model_id, name, tts_voice, languages, voice_demo, remark, sort, creator, create_date, updater, update_date) VALUES ('TTS_HuoshanDoubleStreamTTS_0014', 'TTS_HuoshanDoubleStreamTTS', 'Guangxi Yuanzhou', 'zh_male_guangxiyuanzhou_moon_bigtts', 'Chinese', 'https://lf3-static.bytednsdoc.com/obj/eden-cn/lm_hz_ihsph/ljhwZthlaukjlkulzlp/portal/bigtts/%E5%B9%BF%E8%A5%BF%E8%BF%9C%E8%88%9F.mp3', NULL, 14, 1, NOW(), 1, NOW());
INSERT INTO ai_tts_voice (id, tts_model_id, name, tts_voice, languages, voice_demo, remark, sort, creator, create_date, updater, update_date) VALUES ('TTS_HuoshanDoubleStreamTTS_0015', 'TTS_HuoshanDoubleStreamTTS', 'Sister Jieer', 'zh_female_meituojieer_moon_bigtts', 'Chinese', 'https://lf3-static.bytednsdoc.com/obj/eden-cn/lm_hz_ihsph/ljhwZthlaukjlkulzlp/portal/bigtts/%E5%A6%B9%E5%9D%A8%E6%B4%81%E5%84%BF.mp3', NULL, 15, 1, NOW(), 1, NOW());
INSERT INTO ai_tts_voice (id, tts_model_id, name, tts_voice, languages, voice_demo, remark, sort, creator, create_date, updater, update_date) VALUES ('TTS_HuoshanDoubleStreamTTS_0016', 'TTS_HuoshanDoubleStreamTTS', 'Yuzhou Zixuan', 'zh_male_yuzhouzixuan_moon_bigtts', 'Chinese', 'https://lf3-static.bytednsdoc.com/obj/eden-cn/lm_hz_ihsph/ljhwZthlaukjlkulzlp/portal/bigtts/%E8%B1%AB%E5%B7%9E%E5%AD%90%E8%BD%A9.mp3', NULL, 16, 1, NOW(), 1, NOW());
INSERT INTO ai_tts_voice (id, tts_model_id, name, tts_voice, languages, voice_demo, remark, sort, creator, create_date, updater, update_date) VALUES ('TTS_HuoshanDoubleStreamTTS_0017', 'TTS_HuoshanDoubleStreamTTS', 'Cool Lady', 'zh_female_gaolengyujie_moon_bigtts', 'Chinese', 'https://lf3-static.bytednsdoc.com/obj/eden-cn/lm_hz_ihsph/ljhwZthlaukjlkulzlp/portal/bigtts/%E9%AB%98%E5%86%B7%E5%BE%A1%E5%A7%90.mp3', NULL, 17, 1, NOW(), 1, NOW());
INSERT INTO ai_tts_voice (id, tts_model_id, name, tts_voice, languages, voice_demo, remark, sort, creator, create_date, updater, update_date) VALUES ('TTS_HuoshanDoubleStreamTTS_0018', 'TTS_HuoshanDoubleStreamTTS', 'Proud CEO', 'zh_male_aojiaobazong_moon_bigtts', 'Chinese', 'https://lf3-static.bytednsdoc.com/obj/eden-cn/lm_hz_ihsph/ljhwZthlaukjlkulzlp/portal/bigtts/%E5%82%B2%E5%A8%87%E9%9C%B8%E6%80%BB.mp3', NULL, 18, 1, NOW(), 1, NOW());
INSERT INTO ai_tts_voice (id, tts_model_id, name, tts_voice, languages, voice_demo, remark, sort, creator, create_date, updater, update_date) VALUES ('TTS_HuoshanDoubleStreamTTS_0019', 'TTS_HuoshanDoubleStreamTTS', 'Charming Girlfriend', 'zh_female_meilinvyou_moon_bigtts', 'Chinese', 'https://lf3-static.bytednsdoc.com/obj/eden-cn/lm_hz_ihsph/ljhwZthlaukjlkulzlp/portal/bigtts/%E9%AD%85%E5%8A%9B%E5%A5%B3%E5%8F%8B.mp3', NULL, 19, 1, NOW(), 1, NOW());
INSERT INTO ai_tts_voice (id, tts_model_id, name, tts_voice, languages, voice_demo, remark, sort, creator, create_date, updater, update_date) VALUES ('TTS_HuoshanDoubleStreamTTS_0020', 'TTS_HuoshanDoubleStreamTTS', 'Midnight Podcaster', 'zh_male_shenyeboke_moon_bigtts', 'Chinese', 'https://lf3-static.bytednsdoc.com/obj/eden-cn/lm_hz_ihsph/ljhwZthlaukjlkulzlp/portal/bigtts/%E6%B7%B1%E5%A4%9C%E6%92%AD%E5%AE%A2.mp3', NULL, 20, 1, NOW(), 1, NOW());
INSERT INTO ai_tts_voice (id, tts_model_id, name, tts_voice, languages, voice_demo, remark, sort, creator, create_date, updater, update_date) VALUES ('TTS_HuoshanDoubleStreamTTS_0021', 'TTS_HuoshanDoubleStreamTTS', 'Gentle Girlfriend', 'zh_female_sajiaonvyou_moon_bigtts', 'Chinese', 'https://lf3-static.bytednsdoc.com/obj/eden-cn/lm_hz_ihsph/ljhwZthlaukjlkulzlp/portal/bigtts/%E6%9F%94%E7%BE%8E%E5%A5%B3%E5%8F%8B.mp3', NULL, 21, 1, NOW(), 1, NOW());
INSERT INTO ai_tts_voice (id, tts_model_id, name, tts_voice, languages, voice_demo, remark, sort, creator, create_date, updater, update_date) VALUES ('TTS_HuoshanDoubleStreamTTS_0022', 'TTS_HuoshanDoubleStreamTTS', 'Cute Junior', 'zh_female_yuanqinvyou_moon_bigtts', 'Chinese', 'https://lf3-static.bytednsdoc.com/obj/eden-cn/lm_hz_ihsph/ljhwZthlaukjlkulzlp/portal/bigtts/%E6%92%92%E5%A8%87%E5%AD%A6%E5%A6%B9.mp3', NULL, 22, 1, NOW(), 1, NOW());
INSERT INTO ai_tts_voice VALUES ('TTS_HuoshanDoubleStreamTTS_0023', 'TTS_HuoshanDoubleStreamTTS', 'Kazune (Harmony)', 'multi_male_jingqiangkanye_moon_bigtts', 'Japanese, Spanish', 'https://lf3-static.bytednsdoc.com/obj/eden-cn/lm_hz_ihsph/ljhwZthlaukjlkulzlp/portal/bigtts/Javier.wav', NULL, 23, NULL, NULL, NULL, NULL);
INSERT INTO ai_tts_voice VALUES ('TTS_HuoshanDoubleStreamTTS_0024', 'TTS_HuoshanDoubleStreamTTS', 'Haruko (Sunny)', 'multi_female_shuangkuaisisi_moon_bigtts', 'Japanese, Spanish', 'https://lf3-static.bytednsdoc.com/obj/eden-cn/lm_hz_ihsph/ljhwZthlaukjlkulzlp/portal/bigtts/Esmeralda.mp3', NULL, 24, NULL, NULL, NULL, NULL);
INSERT INTO ai_tts_voice VALUES ('TTS_HuoshanDoubleStreamTTS_0025', 'TTS_HuoshanDoubleStreamTTS', 'Akemi (Vermillion)', 'multi_female_gaolengyujie_moon_bigtts', 'Japanese', 'https://lf3-static.bytednsdoc.com/obj/eden-cn/lm_hz_ihsph/ljhwZthlaukjlkulzlp/portal/bigtts/%E6%9C%B1%E7%BE%8E.mp3', NULL, 25, NULL, NULL, NULL, NULL);
INSERT INTO ai_tts_voice VALUES ('TTS_HuoshanDoubleStreamTTS_0026', 'TTS_HuoshanDoubleStreamTTS', 'Hiroshi (Wide)', 'multi_male_wanqudashu_moon_bigtts', 'Japanese, Spanish', 'https://lf3-static.bytednsdoc.com/obj/eden-cn/lm_hz_ihsph/ljhwZthlaukjlkulzlp/portal/bigtts/Roberto.wav', NULL, 26, NULL, NULL, NULL, NULL);
